services:
  admin:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: nodejs_image
    # '/start' is the shell script used to run the service
    #   command: "node server_consumer.js"
    command:  bash -c "npm install && node server.js"

    #    tty: true           # <-- This option
    # this volume is used to map the files and folders on the host to the container
    # so if we change code on the host, code in the docker container will also be changed
    volumes:
      - .:/app
    # env_file is used to manage the env variables of our project
    environment:
      - NODE_ENV=development
      - PORT=8086
      - COMP_NAME=franceparebrise
    restart: unless-stopped
    ports:
      - 8086:8086
    networks:
      - default
networks:
  default:
    name: network-example
    external: true
